spring:
  application:
    name: userService2-module
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.221.244:3306/cloudtest?autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Zx496267.
#server:
#  port: 8004
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://119.3.221.244:8001/eureka/
mybatis-plus:
  # 修改 mybatis 的 DefaultEnumTypeHandler
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
global-config:
  db-config:
    #逻辑删除定义
    logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
    logic-delete-value: 1 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

redis:
  #单机
  host: 119.3.221.244
  port: 6389
  password:
  #哨兵
  #  database: 1
  #  sentinel:
  #    master: mymaster #指定maser名称
  #    nodes: 119.3.221.244:27001,119.3.221.244:27002,119.3.221.244:27003
  #集群
  #  cluster:
  #    nodes: 119.3.221.244:6379,119.3.221.244:6380,119.3.221.244:6381,119.3.221.244:6382,119.3.221.244:6383,119.3.221.244:6384
  #    max-redirects: 3
  pool:
    maxIdle: 30
    minIdle: 1
    maxActive: 20
    maxWait: -1

# 邮件服务器的SMTP地址，可选，默认为smtp.<发件人邮箱后缀>
host: smtp.yeah.net
# 邮件服务器的SMTP端口，可选，默认25
port: 25
# 发件人（必须正确，否则发送失败）
from: hutool@yeah.net
# 用户名，默认为发件人邮箱前缀
user: hutool
# 密码（注意，某些邮箱需要为SMTP服务单独设置授权码，详情查看相关帮助）
pass: q1w2e3