spring:
  application:
    name: userService3-module
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.221.244:3306/test?autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Zx496267.
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8005
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://119.3.221.244:8001/eureka/

mybatis-plus:
  # 修改 mybatis 的 DefaultEnumTypeHandler
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除定义
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

redis:
  #单机
  host: 119.3.221.244
  port: 6389
  password:
  #哨兵
  #  database: 1
  #  sentinel:
  #    master: mymaster #指定maser名称
  #    nodes: 119.3.221.244:27001,119.3.221.244:27002,119.3.221.244:27003
  #集群
#  cluster:
#    nodes: 119.3.221.244:6379,119.3.221.244:6380,119.3.221.244:6381,119.3.221.244:6382,119.3.221.244:6383,119.3.221.244:6384
#    max-redirects: 3
  pool:
    maxIdle: 30
    minIdle: 1
    maxActive: 20
    maxWait: -1

#seata:
#  tx-service-group: mygroup
#  service:
#    vgroup-mapping:
#      mygroup: seata-server
#  registry:
#    #配置seata注册中心   告诉clint 访问seata server
#    type: eureka
#    eureka:
#      serviceUrl: http://119.3.221.244:8001/eureka
#      application: seata-server
#      weight: 1
#  config:
#    #配置seata配置中心
#    nacos:
#      server-addr: 119.3.221.244:8848
#      username: nacos
#      password: nacos
#      group: DEFAULT_GROUP
#      namespace: 2b88783c-220c-4741-94d5-94585c0314c0
#  client:
#    undo:
#      # 指定undo的序列化协议为protostuff
#      log-serialization: protostuff