spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: userService1-module
#针对Date类型时间，可以做到全局格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudtest?autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: zx496267.
  kafka:
    producer:
      bootstrap:
        servers: 127.0.0.1:9092
      key:
        serializer:
          class: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer:
          class: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      bootstrap:
        servers: 127.0.0.1:9092
      # properties:
      #   security:
      #     protocol: PLAINTEXT
      key:
        serializer:
          class: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer:
          class: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 7003
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

mybatis-plus:
  # 修改 mybatis 的 DefaultEnumTypeHandler
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除定义
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#redis:
#  database: 1
#  host: localhost
#  port: 6379
#  password:
#  pool:
#    maxIdle: 30
#    minIdle: 1
#    maxActive: 20
#    maxWait: -1

redis:
  database: 1
#  host: localhost
#  port: 6379
  password:
  sentinel:
    master: mymaster #指定maser名称
    nodes: 119.3.221.244:27001,119.3.221.244:27002,119.3.221.244:27003
  pool:
    maxIdle: 30
    minIdle: 1
    maxActive: 20
    maxWait: -1


minio:
  url: http://127.0.0.1:9090    #minio启动后的API对应地址
  bucket: test                  #创建的存储桶名称（可界面创建，亦可sdk代码创建）
  accessKey: D2HI8s3y8OmoxCJ3   #Identity 中创建service Acounts 里的
  secretKey: HJvk5MM69nghomgTeoAzI5cXtddoLHJD   #Identity 中创建service Acounts 里的

swagger-agg:
  generate-routes: bacs-auth,bacs-openapi


