spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: userService1-module
  main:
    allow-bean-definition-overriding: true
  #针对Date类型时间，可以做到全局格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.221.244:3306/cloudtest?autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Zx496267.
#server:
#  port: 8003
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://119.3.221.244:8001/eureka/

mybatis-plus:
  # 修改 mybatis 的 DefaultEnumTypeHandler
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除定义
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

redis:
  #单机
  host: 119.3.221.244
  port: 6389
  password:
  #哨兵
#  database: 1
#  sentinel:
#    master: mymaster #指定maser名称
#    nodes: 119.3.221.244:27001,119.3.221.244:27002,119.3.221.244:27003
  #集群
#  cluster:
#    nodes: 119.3.221.244:6379,119.3.221.244:6380,119.3.221.244:6381,119.3.221.244:6382,119.3.221.244:6383,119.3.221.244:6384
#    max-redirects: 3
  pool:
    maxIdle: 30
    minIdle: 1
    maxActive: 20
    maxWait: -1

minio:
  url: http://127.0.0.1:9090    #minio启动后的API对应地址
  bucket: test                  #创建的存储桶名称（可界面创建，亦可sdk代码创建）
  accessKey: D2HI8s3y8OmoxCJ3   #Identity 中创建service Acounts 里的
  secretKey: HJvk5MM69nghomgTeoAzI5cXtddoLHJD   #Identity 中创建service Acounts 里的



#seata:
#  tx-service-group: mygroup
#  service:
#    vgroup-mapping:
#      mygroup: seata-server
#  registry:
#    #配置seata注册中心   告诉clint 访问seata server
#    type: eureka
#    eureka:
#      serviceUrl: http://119.3.221.244:8001/eureka
#      application: seata-server
#      weight: 1
#  config:
#    #配置seata配置中心
#    nacos:
#      server-addr: 119.3.221.244:8848
#      username: nacos
#      password: nacos
#      group: DEFAULT_GROUP
#      namespace: 2b88783c-220c-4741-94d5-94585c0314c0
#  client:
#    undo:
#      # 指定undo的序列化协议为protostuff
#      log-serialization: protostuff
#xxl:
#  job:
#    accessToken:
#    admin:
#      addresses: http://localhost:8087/xxl-job-admin/
#    executor:
#      appname: userService1-module
#      address:
#      ip:
#      port: 9997
#      logpath: ./logs
#      logretentiondays: 30

